ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_id_project_workspace_uq" UNIQUE("id","project_id","workspace_id");--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_id_task_project_workspace_uq" UNIQUE("id","task_id","project_id","workspace_id");--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_project_workspace_fk" FOREIGN KEY ("project_id","workspace_id") REFERENCES "public"."projects"("id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_task_project_fk" FOREIGN KEY ("task_id","project_id","workspace_id") REFERENCES "public"."tasks"("id","project_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_run_workspace_fk" FOREIGN KEY ("agent_run_id","workspace_id") REFERENCES "public"."agent_runs"("id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_run_project_fk" FOREIGN KEY ("agent_run_id","project_id","workspace_id") REFERENCES "public"."agent_runs"("id","project_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_run_task_fk" FOREIGN KEY ("agent_run_id","task_id","project_id","workspace_id") REFERENCES "public"."agent_runs"("id","task_id","project_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "findings" ADD CONSTRAINT "findings_run_project_fk" FOREIGN KEY ("agent_run_id","project_id","workspace_id") REFERENCES "public"."agent_runs"("id","project_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "findings" ADD CONSTRAINT "findings_run_task_fk" FOREIGN KEY ("agent_run_id","task_id","project_id","workspace_id") REFERENCES "public"."agent_runs"("id","task_id","project_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
