ALTER TABLE "checkpoints" ADD CONSTRAINT "checkpoints_handoff_scope_uq" UNIQUE("id","runtime_session_id","orchestrator_id","workspace_id");--> statement-breakpoint
ALTER TABLE "execution_digests" ADD CONSTRAINT "execution_digests_session_workspace_uq" UNIQUE("id","runtime_session_id","workspace_id");--> statement-breakpoint
ALTER TABLE "execution_jobs" ADD CONSTRAINT "execution_jobs_digest_scope_uq" UNIQUE("id","runtime_session_id","workspace_id");--> statement-breakpoint
ALTER TABLE "execution_digests" ADD CONSTRAINT "execution_digests_job_scope_fk" FOREIGN KEY ("execution_job_id","runtime_session_id","workspace_id") REFERENCES "public"."execution_jobs"("id","runtime_session_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runtime_handoffs" ADD CONSTRAINT "runtime_handoffs_task_scope_fk" FOREIGN KEY ("task_id","operation_id") REFERENCES "public"."tasks"("id","operation_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runtime_handoffs" ADD CONSTRAINT "runtime_handoffs_checkpoint_scope_fk" FOREIGN KEY ("checkpoint_id","predecessor_session_id","orchestrator_id","workspace_id") REFERENCES "public"."checkpoints"("id","runtime_session_id","orchestrator_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runtime_handoffs" ADD CONSTRAINT "runtime_handoffs_digest_scope_fk" FOREIGN KEY ("digest_id","predecessor_session_id","workspace_id") REFERENCES "public"."execution_digests"("id","runtime_session_id","workspace_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runtime_handoffs" ADD CONSTRAINT "runtime_handoffs_scope_ck" CHECK ("runtime_handoffs"."task_id" is null or "runtime_handoffs"."operation_id" is not null);--> statement-breakpoint
ALTER TABLE "runtime_handoffs" ADD CONSTRAINT "runtime_handoffs_progress_ck" CHECK (("runtime_handoffs"."status" = 'requested') or ("runtime_handoffs"."checkpoint_id" is not null and ("runtime_handoffs"."status" = 'checkpointed' or "runtime_handoffs"."successor_session_id" is not null)));
